title: welcome to this
author: Aulyaukaurcaue
email: aliakarcaue@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  we will proceed with some establishment.

# social links
twitter_username: aulyaukaurcaue # DO NOT include the @ character, or else the build will fail!
github_username: aliakarca # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-midnight
